[project]
name = "chess-game-outcome-predictor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mohamed Ibrahim", email = "mohamedhassen.ibrahim@mail.utoronto.ca" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "python-chess>=1.999",
    "scikit-learn>=1.9.1",
]

[project.scripts]
chess-game-outcome-predictor = "chess_game_outcome_predictor:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
